### ISSUE TITLE
最新版Chrome无法启用

### ISSUE THREAD

**Issue by akring** [xmcp/GoFW#2]
Chrome 49安装后提示：“并非来自 chrome 网上应用店”，可以在扩展列表里看到，但是无法点击启用，可能只能考虑上架Chrome商店了（Mac无法修改策略。。。）

**Comment by xmcp** [comment]
这是已知问题。学生党没有信用卡，暂时不考虑上架chrome webstore。如果你非常需要这个功能，可以fork之后自己上架，我不反对。另外OSX好像是有chromium的吧？

**Comment by akring** [comment]
OK，那我再找找其他解决方案
