### ISSUE TITLE
另一个拓展，另一个功能

### ISSUE THREAD

**Issue by Crystal-RainSlide** [xmcp/GoFW#3]
这是另一个功能近似的拓展，给你们互相介绍认识一下----加速器和这个gooreplacer是我用过的 接近十个
 CDN修改类拓展 中最好的两个，希望加速器能做自定义规则，导入导出等功能，gooreplacer能内置更多规则。
https://github.com/jiacai2050/gooreplacer4chrome

**Comment by xmcp** [comment]
我目前主要精力在搞 [pakku.js](https://github.com/xmcp/pakku.js)，讲真这个东西我真的不想维护了┑(￣Д ￣)┍

所以目前的状态就是我现在基本只修一些GoFW的恶性bug（比如把IP定位砍掉什么的233）。
不过话说gooreplacer4chrome真的不错哟。

**Comment by xmcp** [comment]
总之：
- GoFW只是我编给自己用的一个扩展，我正好有一个开发者账号就传到webstore上了（没想到还有不少人用）
- 所以我并不打算加这些强大的自定义规则（因为如果我想自定义我就直接改现在的代码了）
- 如果你希望GoFW加入自定义规则的话，欢迎发PR过来
- 欢迎使用gooreplacer4chrome :smirk_cat:

**Comment by Crystal-RainSlide** [comment]
OK

我已经全fork走了，打算合并为一个自带更多规则的gooreplacer4chrome
（Firefox拓展新出的一堆堆堆堆安全机制搞不来，暂时不搞）
鉴于这招用途很多，甚至可以用来对付流氓导航……
感觉以后可能会挊到Adblock们的规模，联网更新规则列表…

**Comment by xmcp** [comment]
这些就在我的需求之外了 :rofl: 
毕竟 GoFW 本身只是我上 stackoverflow 不爽偶然搞出来的，并不需要代替 ABP 之类的
